// <auto-generated />
namespace eth.Eve.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EveSpace_TokenLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EveSpace_TokenLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201605312049249_EveSpace_TokenLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
