// <auto-generated />
using eth.Eve.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace eth.Eve.Storage.Migrations
{
    [DbContext(typeof(EveDb))]
    [Migration("20171115100729_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eth.Eve.Storage.Model.EveSpace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BotApiAccessToken")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.ToTable("EveSpaces");
                });

            modelBuilder.Entity("eth.Eve.Storage.Model.PluginStoreBinary", b =>
                {
                    b.Property<long>("SpaceId");

                    b.Property<Guid>("PluginGuid");

                    b.Property<string>("Key");

                    b.Property<string>("Metadata");

                    b.Property<string>("PluginVersion");

                    b.Property<byte[]>("Value")
                        .IsRequired();

                    b.HasKey("SpaceId", "PluginGuid", "Key");

                    b.ToTable("PluginStoreBinaries");
                });

            modelBuilder.Entity("eth.Eve.Storage.Model.PluginStoreString", b =>
                {
                    b.Property<long>("SpaceId");

                    b.Property<Guid>("PluginGuid");

                    b.Property<string>("Key");

                    b.Property<string>("PluginVersion");

                    b.Property<string>("Value");

                    b.HasKey("SpaceId", "PluginGuid", "Key");

                    b.ToTable("PluginStoreStrings");
                });

            modelBuilder.Entity("eth.Eve.Storage.Model.PluginStoreBinary", b =>
                {
                    b.HasOne("eth.Eve.Storage.Model.EveSpace")
                        .WithMany("PluginStoreBinaries")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("eth.Eve.Storage.Model.PluginStoreString", b =>
                {
                    b.HasOne("eth.Eve.Storage.Model.EveSpace")
                        .WithMany("PluginStoreStrings")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
